import bcrypt from "bcrypt";

export const users = [
  {
    id: "uuid-1",
    full_name: "Joan Doe",
    email: "admin@example.com",
    password: bcrypt.hashSync("123456", 10),
    role: "admin",
  },
  {
    id: "uuid-2",
    full_name: "John Smith",
    email: "user@example.com",
    password: bcrypt.hashSync("123456", 10),
    role: "employee",
  },
  {
    id: "uuid-3",
    full_name: "Alice Johnson",
    email: "alice@example.com",
    password: bcrypt.hashSync("123456", 10),
    role: "employee",
  },
  {
    id: "uuid-4",
    full_name: "Bob Williams",
    email: "bob@example.com",
    password: bcrypt.hashSync("123456", 10),
    role: "employee",
  },
];

export const emails = [
  {
    id: "uuid-1",
    email: "admin@example.com",
  },
  {
    id: "uuid-2",
    email: "user@example.com",
  },
  {
    id: "uuid-3",
    email: "alice@example.com",
  },
  {
    id: "uuid-4",
    email: "bob@example.com",
  },
];

export const tasks = [
  {
    id: "uuid-task-1",
    company: "TechCorp",
    project: "Website Redesign",
    task_type: "Development",
    task_description: "Refactor homepage layout",
    entry_time: "09:00:00",
    exit_time: "17:00:00",
    lunch_hours: 1,
    status: false,
    user_id: "uuid-1",
    task_date: "2025-01-31",
  },
  {
    id: "uuid-task-2",
    company: "TechCorp",
    project: "API Development",
    task_type: "Backend",
    task_description: "Build authentication module",
    entry_time: "10:00:00",
    exit_time: "18:00:00",
    lunch_hours: 1,
    status: true,
    user_id: "uuid-1",
    task_date: "2025-01-31",
  },
  {
    id: "uuid-task-3",
    company: "SoftSolutions",
    project: "Mobile App",
    task_type: "Testing",
    task_description: "Perform UI testing on new feature",
    entry_time: "10:00:00",
    exit_time: "18:00:00",
    lunch_hours: 1,
    status: true,
    user_id: "uuid-2",
    task_date: "2025-01-31",
  },
  {
    id: "uuid-task-4",
    company: "SoftSolutions",
    project: "Bug Fixes",
    task_type: "Development",
    task_description: "Fix login issue on Android",
    entry_time: "09:30:00",
    exit_time: "17:30:00",
    lunch_hours: 1,
    status: false,
    user_id: "uuid-2",
    task_date: "2025-01-31",
  },
  {
    id: "uuid-task-5",
    company: "NextGenTech",
    project: "AI Integration",
    task_type: "Research",
    task_description: "Explore machine learning models",
    entry_time: "08:00:00",
    exit_time: "16:00:00",
    lunch_hours: 1,
    status: false,
    user_id: "uuid-3",
    task_date: "2025-01-31",
  },
  {
    id: "uuid-task-6",
    company: "NextGenTech",
    project: "API Development",
    task_type: "Backend",
    task_description: "Implement data caching",
    entry_time: "10:00:00",
    exit_time: "18:00:00",
    lunch_hours: 1,
    status: true,
    user_id: "uuid-3",
    task_date: "2025-01-31",
  },
  {
    id: "uuid-task-7",
    company: "WebSolutions",
    project: "E-commerce Website",
    task_type: "Frontend",
    task_description: "Redesign product listing page",
    entry_time: "09:00:00",
    exit_time: "17:00:00",
    lunch_hours: 1,
    status: false,
    user_id: "uuid-4",
    task_date: "2025-01-31",
  },
  {
    id: "uuid-task-8",
    company: "WebSolutions",
    project: "Checkout Optimization",
    task_type: "Development",
    task_description: "Improve payment process speed",
    entry_time: "10:00:00",
    exit_time: "18:00:00",
    lunch_hours: 1,
    status: true,
    user_id: "uuid-4",
    task_date: "2025-01-31",
  },
];
